/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_MainWindow (void);
GtkWidget* create_ProjectOptionsDialogue (void);
GtkWidget* create_ExecutionWindow (void);
GtkWidget* create_AboutDialogue (void);
GtkWidget* create_ConsoleWindow (void);
GtkWidget* create_DirectoryDialogue (void);
GtkWidget* create_OptionsDialogue (void);
GtkWidget* create_AddFileDialogue (void);
GtkWidget* create_KillAllConfirmDialogue (void);
GtkWidget* create_BuiltinLibOptionsDialogue (void);
GtkWidget* create_FileDialogue (void);
GtkWidget* create_TestOptionsDialogue (void);
GtkWidget* create_ImplementationOptionsDialogue (void);
GtkWidget* create_FileSaveDialogue (void);
